# Generated by Django 5.1.6 on 2025-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitoterapico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
                ('propriedades', models.TextField()),
                ('indicacao', models.TextField()),
                ('modo_uso', models.TextField()),
                ('dosagem', models.TextField()),
                ('efeito_colateral', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
