# Generated by Django 5.1.6 on 2025-03-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitoterapico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitoterapico',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fitoterapico',
            name='dosagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
