# Generated by Django 5.1.6 on 2025-03-01 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitoterapico', '0002_fitoterapico_tipo_alter_fitoterapico_dosagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fitoterapico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitoterapico_tipo', to='fitoterapico.tipo'),
        ),
    ]
