# Generated by Django 5.1.6 on 2025-03-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitoterapico', '0003_tipo_alter_fitoterapico_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo',
            old_name='name',
            new_name='nome',
        ),
    ]
