# Generated by Django 5.1.6 on 2025-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitoterapico', '0005_fitoterapico_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitoterapicoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitoterapico_count', models.IntegerField()),
                ('fitoterapico_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
